spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ghsicilianotfi
    username: root
    password: root12345678
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.MySQL5Dialect
  thymeleaf:
    cache: false
